overview:
  title: Product Image Grid
  image: logo.png
  description: Shows how a product grid could look with ImageGrid used.
  order: 3
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/misc-menu.yml
      footer: true
      fsi:
        imageGrid: true
      bootstrap:
        icons: true
  mapping:
    html: "index.html"
    css: "prodgrid.css"
    js: "prodgrid.js"
jsfiddle:
  deploy: true
