overview:
  title: Photographer Portfolio
  image: logo.png
  description: Shows how a portfolio could be displayed with ImageGrid and Metadata used. On click a zoom viewer with the image is opened via modal.
  order: 4
sample:
  template:
    schema: framework-2023
    components:
      menu:
        template: data/misc-menu.yml
      footer: true
      fsi:
        viewer: true
        imageGrid: true
      bootstrap:
        icons: true
  mapping:
    html: "index.html"
    css: "portfolio.css"
    js: "portfolio.js"
jsfiddle:
  deploy: true
